const products = [

  {
    id: "red-velvet-royale",
    name: "Red Velvet Royale",
    shortDesc: "Velvety crimson layers with cream cheese",
    description:
      "A showstopper in every sense — vibrant red cocoa sponge layers sandwiched with tangy cream cheese frosting, finished with a smooth outer coat and dramatic red velvet crumble on top. This elegant cake balances sweetness and tartness in every bite.",
    price: 899,
    weight: "1 kg",
    serves: "8–10",
    tag: "BestSeller",
    emoji: "❤️",
    image: "/images/Red Velvet Royale.jpg",
    thumb: "/images/Red-Velvet-Royale-1.jpg",
  },

  {
    id: "black-forest-cake",
    name: "Black Forest Cake",
    shortDesc: "Chocolate layers with cherries & cream",
    description:
      "A timeless classic made with rich chocolate sponge layered with fresh whipped cream and juicy cherries. Topped with chocolate shavings and cherries, this cake delivers the perfect balance of sweetness and freshness.",
    price: 750,
    weight: "1 kg",
    serves: "8–10",
    tag: "BestSeller",
    emoji: "🍒",
    image: "/images/Black Forest Cake.jpg",
    thumb: "/images/Black Forest Cake-1.jpg",
  },

  {
    id: "white-forest-cake",
    name: "White Forest Cake",
    shortDesc: "Vanilla sponge with white chocolate flakes",
    description:
      "A delightful twist on the classic forest cake, featuring soft vanilla sponge layers with whipped cream and cherries. Decorated with white chocolate shavings for a light, creamy experience.",
    price: 780,
    weight: "1 kg",
    serves: "8–10",
    tag: "BestSeller",
    emoji: "🤍",
    image: "/images/White Forest Cake.jpg",
    thumb: "/images/White Forest Cake-1.jpg",
  },

  {
    id: "choco-truffle-cake",
    name: "Choco Truffle Cake",
    shortDesc: "Rich chocolate ganache indulgence",
    description:
      "A dream for chocolate lovers — layers of moist chocolate sponge filled and coated with silky smooth chocolate ganache. Deep, rich, and irresistibly indulgent.",
    price: 820,
    weight: "1 kg",
    serves: "8–10",
    tag: "Premium",
    emoji: "🍫",
    image: "/images/Choco Truffle Cake.jpg",
    thumb: "/images/Choco Truffle Cake-1.jpg",
  },

  {
    id: "butterscotch-cake",
    name: "Butterscotch Cake",
    shortDesc: "Crunchy caramel with cream layers",
    description:
      "A delicious blend of buttery caramel flavor and crunchy praline. Soft sponge layered with butterscotch cream and topped with caramel drizzle and crispy bits.",
    price: 700,
    weight: "1 kg",
    serves: "8–10",
    tag: "BestSeller",
    emoji: "🍯",
    image: "/images/Butterscotch Cake.jpg",
    thumb: "/images/Butterscotch Cake-1.jpg",
  },

  {
    id: "pineapple-cake",
    name: "Pineapple Cake",
    shortDesc: "Fresh pineapple with whipped cream",
    description:
      "A refreshing and light cake made with soft sponge layers, whipped cream, and juicy pineapple chunks. Perfect for those who love fruity flavors.",
    price: 650,
    weight: "1 kg",
    serves: "8–10",
    tag: "Classic",
    emoji: "🍍",
    image: "/images/Pineapple Cake.jpg",
    thumb: "/images/Pineapple Cake-1.jpg",
  },

  {
    id: "grape-cake",
    name: "Grape Cake",
    shortDesc: "Sweet grape flavor with creamy layers",
    description:
      "A unique and delightful cake infused with fresh grape flavor, layered with soft cream and topped with juicy grapes for a refreshing taste.",
    price: 680,
    weight: "1 kg",
    serves: "8–10",
    tag: "Classic",
    emoji: "🍇",
    image: "/images/Grape Cake.jpg",
    thumb: "/images/Grape Cake-1.jpg",
  },
  {
  id: "blueberry-bliss-cake",
  name: "Blueberry Bliss Cake",
  shortDesc: "Fresh blueberry layers with creamy frosting",
  description:
    "A delightful fusion of soft vanilla sponge layered with rich whipped cream and luscious blueberry compote. Topped with glossy blueberry glaze and fresh berries, this cake offers a perfect balance of sweetness and tangy freshness in every bite.",
  price: 820,
  weight: "1 kg",
  serves: "8–10",
  tag: "Classic",
  emoji: "🫐",
  image: "https://i.pinimg.com/avif/736x/4e/3e/17/4e3e174eb22f796506eb58686e61eec6.avf",
  thumb: "https://i.pinimg.com/1200x/0a/38/30/0a383002f70870fb7146796146c8c179.jpg",
},


  // 🔥 PREMIUM CAKES
  {
    id: "oreo-cake",
    name: "Oreo Cake",
    shortDesc: "Chocolate cake with Oreo crunch",
    description: "Rich chocolate sponge layered with Oreo cream and crunchy biscuit bits.",
    price: 800,
    weight: "1 kg",
    serves: "8–10",
    tag: "Premium",
    emoji: "🍪",
    image: "https://i.pinimg.com/1200x/28/1a/56/281a5601f5498a6f20da2770af82485d.jpg",
    thumb: "https://i.pinimg.com/736x/bc/81/06/bc81061be33d4d377288d99937873e1d.jpg",
  },
  {
    id: "rose-milk-cake",
    name: "Rose Milk Cake",
    shortDesc: "Floral rose milk flavor",
    description: "Soft sponge infused with rose milk and layered with smooth cream.",
    price: 800,
    weight: "1 kg",
    serves: "8–10",
    tag: "Premium",
    emoji: "🌹",
    image: "https://i.pinimg.com/736x/83/74/7f/83747f4001926c2263b599dc9a0938b1.jpg",
    thumb: "/images/Rose-milk-cake.jpg",
  },
  {
    id: "rainbow-cake",
    name: "Rainbow Cake",
    shortDesc: "Colorful layered cake",
    description: "Vibrant multi-layer sponge cake with creamy frosting.",
    price: 1000,
    weight: "1 kg",
    serves: "8–10",
    tag: "Classic",
    emoji: "🌈",
    image: "https://i.pinimg.com/736x/a5/70/45/a570459fccea3d9afd94dd548dc9e15e.jpg",
    thumb: "https://i.pinimg.com/1200x/d9/3d/2e/d93d2e25820fe21fe0396f769c595c05.jpg",
  },
  {
    id: "caramel-cake",
    name: "Caramel Cake",
    shortDesc: "Sweet caramel flavor",
    description: "Soft sponge layered with caramel cream and topped with glaze.",
    price: 1000,
    weight: "1 kg",
    serves: "8–10",
    tag: "Premium",
    emoji: "🍮",
    image: "https://i.pinimg.com/1200x/71/03/80/7103807d6f23a3d52384f348e40b6a98.jpg",
    thumb: "https://i.pinimg.com/736x/09/bd/bb/09bdbb0ea6369577289b331fa166210e.jpg",
  },
  {
    id: "ferrero-rocher-cake",
    name: "Ferrero Rocher Cake",
    shortDesc: "Hazelnut chocolate delight",
    description: "Rich chocolate cake infused with Ferrero Rocher flavor.",
    price: 1100,
    weight: "1 kg",
    serves: "8–10",
    tag: "Premium",
    emoji: "🍫",
    image: "https://i.pinimg.com/1200x/8f/5e/25/8f5e25fa966a28211ec02551257fee58.jpg",
    thumb: "https://i.pinimg.com/736x/f6/71/79/f671791b569f6242aaf92fdc09128b80.jpg",
  },

  // 🍍 ALL TIME FAVORITE
  {
    id: "mango-cake",
    name: "Mango Cake",
    shortDesc: "Sweet mango cake",
    description: "Layered sponge with mango pulp and whipped cream.",
    price: 700,
    weight: "1 kg",
    serves: "8–10",
    tag: "Favorite",
    emoji: "🥭",
    image: "https://i.pinimg.com/736x/65/16/8c/65168c6d0b64bfce0a8b77ea42f48b94.jpg",
    thumb: "https://i.pinimg.com/736x/44/16/0f/44160f48890a9930bbbb2f42622aeecd.jpg",
  },
  {
    id: "lychee-cake",
    name: "Lychee Cake",
    shortDesc: "Light lychee flavor cake",
    description: "Refreshing cake with lychee essence and cream.",
    price: 700,
    weight: "1 kg",
    serves: "8–10",
    tag: "Favorite",
    emoji: "🍈",
    image: "https://i.pinimg.com/736x/99/80/fc/9980fcec3477478c1edaff69e5907c58.jpg",
    thumb: "https://i.pinimg.com/736x/ee/8c/11/ee8c11494bc16c6ea03405cd642b0fd1.jpg",
  },
  {
    id: "strawberry-cake",
    name: "Strawberry Cake",
    shortDesc: "Fresh strawberry cake",
    description: "Soft sponge layered with strawberry cream.",
    price: 700,
    weight: "1 kg",
    serves: "8–10",
    tag: "Favorite",
    emoji: "🍓",
    image: "https://i.pinimg.com/1200x/54/2b/10/542b1085cb198b6868085f56386fc365.jpg",
    thumb: "https://i.pinimg.com/736x/50/f8/e2/50f8e21a7c97de3567a0fbd93592697a.jpg",
  },

 

  // 🥜 NUTS LOVERS
  
  {
    id: "pistachio-cake",
    name: "Pistachio Cream Cake",
    shortDesc: "Rich pistachio flavor",
    description: "Delicious pistachio cream layered cake.",
    price: 800,
    weight: "1 kg",
    serves: "8–10",
    tag: "Premium",
    emoji: "🥜",
    image: "https://i.pinimg.com/1200x/32/35/c8/3235c8bc1059294383c3edf17100ed73.jpg",
    thumb: "https://i.pinimg.com/1200x/51/da/a5/51daa59563cad360278a004d7869254a.jpg",
  },

  // 🍫 CHOCOLATE FUSION
  {
    id: "choco-strawberry-cake",
    name: "Choco Strawberry Cake",
    shortDesc: "Chocolate + strawberry combo",
    description: "Perfect blend of chocolate sponge and strawberry cream.",
    price: 800,
    weight: "1 kg",
    serves: "8–10",
    tag: "BestSeller",
    emoji: "🍓",
    image: "https://i.pinimg.com/1200x/22/c0/dc/22c0dcaf6dcd9947566b6bc66b4a385e.jpg",
    thumb: "https://i.pinimg.com/1200x/c6/bb/da/c6bbdae9c2eb7a4c7824e9e95ae958d6.jpg",
  },
  {
    id: "choco-pineapple-cake",
    name: "Choco Pineapple Cake",
    shortDesc: "Chocolate with pineapple twist",
    description: "Unique combination of chocolate and pineapple flavor.",
    price: 800,
    weight: "1 kg",
    serves: "8–10",
    tag: "BestSeller",
    emoji: "🍍",
    image: "https://i.pinimg.com/1200x/a7/3a/e6/a73ae6fc5951fde1f407e6387bd4b89b.jpg",
    thumb: "https://i.pinimg.com/736x/77/e1/a1/77e1a1e1cc610a7d1e5bdb49d67992b3.jpg",
  },
  {
  id: "classic-chocolate-brownie",
  name: "Classic Chocolate Brownie",
  shortDesc: "Rich fudgy chocolate brownie",
  description: "A dense and fudgy chocolate brownie with a deep cocoa flavor, perfect for true chocolate lovers.",
  price: 250,
  weight: "250 g",
  serves: "1–2",
  tag: "Brownies",
  emoji: "🍫",
  image: "https://i.pinimg.com/1200x/63/56/3a/63563afc61da49b7f827f6f82037f587.jpg",
  thumb: "https://i.pinimg.com/1200x/3f/b0/eb/3fb0eb836ff71a4bb8c0a32824e58a85.jpg",
},
{
  id: "walnut-brownie",
  name: "Walnut Brownie",
  shortDesc: "Chocolate brownie with crunchy walnuts",
  description: "A rich chocolate brownie loaded with crunchy walnuts, giving a perfect mix of texture and taste.",
  price: 300,
  weight: "250 g",
  serves: "1–2",
  tag: "Brownies",
  emoji: "🌰",
  image: "https://i.pinimg.com/736x/c2/4d/86/c24d86e0e5f5027fd5a215cd8fb78406.jpg",
  thumb: "https://i.pinimg.com/736x/99/b7/70/99b7707aad5de7d3bf23f0d1b7cdd05c.jpg",
},
{
  id: "choco-chip-brownie",
  name: "Choco Chip Brownie",
  shortDesc: "Brownie filled with chocolate chips",
  description: "Soft and gooey brownie packed with melted chocolate chips in every bite.",
  price: 280,
  weight: "250 g",
  serves: "1–2",
  tag: "Brownies",
  emoji: "🍪",
  image: "https://i.pinimg.com/1200x/5a/1a/27/5a1a27cf2345aec603bc2bbfef165cc2.jpg",
  thumb: "https://i.pinimg.com/1200x/48/ae/12/48ae12d767fb1f638d630d1715d99afa.jpg",
},
{
  id: "oreo-brownie",
  name: "Oreo Brownie",
  shortDesc: "Brownie with Oreo crunch",
  description: "Delicious brownie layered with Oreo biscuits and cream for an extra crunchy treat.",
  price: 320,
  weight: "250 g",
  serves: "1–2",
  tag: "Brownies",
  emoji: "🍪",
  image: "https://i.pinimg.com/736x/f3/81/41/f38141a2361d019580a93b528cb43636.jpg",
  thumb: "https://i.pinimg.com/1200x/50/ed/c0/50edc0af2735184560c42bf901ac94f8.jpg",
},
{
  id: "caramel-brownie",
  name: "Caramel Brownie",
  shortDesc: "Chocolate brownie with caramel filling",
  description: "A soft chocolate brownie filled with gooey caramel, offering a sweet and rich flavor combination.",
  price: 300,
  weight: "250 g",
  serves: "1–2",
  tag: "Brownies",
  emoji: "🍯",
  image: "https://i.pinimg.com/1200x/fc/a9/2f/fca92f47c7c4bfc5c6f5640a48fa5571.jpg",
  thumb: "https://i.pinimg.com/736x/36/78/d9/3678d9b5f33eba56afc7b3a6e26d7c5e.jpg",
}

];